[global]
        server string = Backup Sidecar
        idmap config * : range = 3000-7999
        security = user
        server min protocol = SMB3
        smb encrypt = required

        # disable printing services
        load printers = no
        printing = bsd
        printcap name = /dev/null
        disable spoolss = yes

[Backups]
        path = /storage/backups
        comment = Shared
        valid users = @smb
        browseable = yes
        writable = no
        read only = yes
        force user = root
        force group = root