#-[ PROJECT NAME
name: actualbudget
# https://actualbudget.org
# https://github.com/actualbudget/actual

services:
  # Actual Budget - Personal Finance and Budgeting Tool
  actualbudget:
    image: docker.io/actualbudget/actual-server:${ACTUAL_SERVER_IMAGE_TAG}
    container_name: actualbudget
    healthcheck:
      test: ['CMD-SHELL', 'node scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    environment:
      - ACTUAL_ALLOWED_LOGIN_METHODS=${ACTUAL_ALLOWED_LOGIN_METHODS}
      - ACTUAL_LOGIN_METHOD=${ACTUAL_LOGIN_METHOD}
      - ACTUAL_OPENID_DISCOVERY_URL=${ACTUAL_OPENID_DISCOVERY_URL}
      - ACTUAL_OPENID_CLIENT_ID=${ACTUAL_OPENID_CLIENT_ID}
      - ACTUAL_OPENID_CLIENT_SECRET=${ACTUAL_OPENID_CLIENT_SECRET}
      - ACTUAL_OPENID_SERVER_HOSTNAME=${ACTUAL_OPENID_SERVER_HOSTNAME}
    networks:
      # Default Port: 5006
      - cloudflare-ingress
    restart: unless-stopped
    volumes:
      - actualbudget.data:/data
      - ./config.json:/data/config.json:ro

networks:
  # Public / External Network (Cloudflare Tunnel)
  cloudflare-ingress:
    external: true

volumes:
  actualbudget.data:
    name: actualbudget.data
