#-[ PROJECT NAME
name: bentopdf
# https://www.bentopdf.com/
# https://github.com/alam00000/bentopdf

services:
   # BentoPDF - Free and FOSS PDF Tools
  bentopdf:
    image: ghcr.io/alam00000/bentopdf-simple:${BENTOPDF_IMAGE_TAG:-latest}
    container_name: bentopdf
    networks:
      # Default Port: 8080
      - cloudflare-ingress
    restart: unless-stopped

networks:
  # Public / External Network (Cloudflare Tunnel)
  cloudflare-ingress:
    external: true
