#-[ PROJECT NAME
name: stirling-pdf
# https://stirling.com/
# https://github.com/Stirling-Tools/stirling-pdf

services:
  # Like Adobe Acrobat, but I don't have to sell my organs to use it
  stirling-pdf:
    image: stirlingtools/stirling-pdf:${STIRLING_PDF_IMAGE_TAG}
    container_name: stirling-pdf
    environment:
    networks:
      - cloudflare-ingress
    restart: unless-stopped
    volumes:
      - stirling-pdf.data:/configs              # Settings & database
      - stirling-pdf.pipeline:/pipeline         # Automation configs

networks:
  # Public / External Network (Cloudflare Tunnel)
  cloudflare-ingress:
    external: true

volumes:
  stirling-pdf.data:
    name: stirling-pdf.data
  stirling-pdf.pipeline:
    name: stirling-pdf.pipeline
