#-[ PROJECT NAME
name: dockflare
# https://dockflare.app/
# https://github.com/ChrispyBacon-dev/DockFlare

services:
  # Docker Socket Proxy - Always use protection
  dockflare-socket-proxy:
    image: tecnativa/docker-socket-proxy:${SOCKET_PROXY_IMAGE_TAG}
    container_name: dockflare-socket-proxy
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - CONTAINERS=1
      - EVENTS=1
      - NETWORKS=1
      - IMAGES=1
      - POST=1
      - PING=1
      - INFO=1
      - EXEC=1
    networks:
      - dockflare-backend
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Init Only - Set Volume permissions
  dockflare-init:
    image: alpine:${ALPINE_IMAGE_TAG}
    command: ["sh", "-c", "chown -R ${DOCKFLARE_UID:-65532}:${DOCKFLARE_GID:-65532} /app/data"]
    container_name: dockflare-init
    networks:
      - dockflare-backend
    restart: no
    volumes:
      - dockflare.data:/app/data

  # Dockflare - Cloudflare Tunnel, Access, and DNS Automation Using Docker Labels
  dockflare:
    image: alplat/dockflare:${DOCKFLARE_IMAGE_TAG}
    container_name: dockflare
    depends_on:
      socket-proxy:
        condition: "service_started"
      dockflare-init:
        condition: "service_completed_successfully"
      redis:
        condition: "service_started"
    env_file: "./.env"
    networks:
      # Default Port: 5000
      - "cloudflare"
      - "private"
    restart: "unless-stopped"
    volumes:
      - "dockflare.data:/app/data"

  # Redis - Key/Value Store
  redis:
    image: "redis:${REDIS_IMAGE_TAG}"
    container_name: "redis"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks:
      - "private"
    restart: "unless-stopped"
    volumes:
      - "redis.data:/data"

#-[ NETWORKS
networks:
  # Public / External Network (Cloudflare Tunnel)
  cloudflare:
    external: true
  # Storage / Backend Network (Not Accessible Externally)
  private:
    driver: "bridge"

#-[ VOLUMES
volumes:
  dockflare.data:
  redis.data:
