#-[ PROJECT NAME
name: omni-tools
# https://omnitools.app/
# https://github.com/iib0011/omni-tools

services:
  # OmniTools - Toolkit for editing images, text, lists, data
  omni-tools:
    image: iib0011/omni-tools:${OMNI_TOOLS_IMAGE_TAG:-latest}
    container_name: omni-tools
    networks:
      # Default Port: 80
      - cloudflare-ingress
    restart: unless-stopped

networks:
  # Public / External Network (Cloudflare Tunnel)
  cloudflare-ingress:
    external: true
