#-[ PROJECT NAME
name: caddy
# https://caddyserver.com/
# https://github.com/caddyserver/caddy

services:
  # Caddy - Reverse Proxy
  caddy:
    build:
      context: .
      dockerfile: ./caddy/Dockerfile
    container_name: caddy
    environment:
      - BASE_URL=${BASE_URL}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - SSL_EMAIL=${SSL_EMAIL}
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - caddy
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy.data:/data

networks:
  caddy:
    driver: bridge
    name: caddy

volumes:
  caddy.data:
    name: caddy.data
