#-[ PROJECT NAME
name: cyberchef
# https://gchq.github.io/CyberChef/
# https://github.com/gchq/CyberChef

services:
  # CyberChef - Cyber Swiss Army Knife
  cyberchef:
    image: ghcr.io/gchq/cyberchef:${CYBERCHEF_IMAGE_TAG:-latest}
    container_name: cyberchef
    networks:
      # Default Port: 8080
      - cloudflare-ingress
    restart: unless-stopped

networks:
  # Public / External Network (Cloudflare Tunnel)
  cloudflare-ingress:
    external: true
