#-[ PROJECT NAME
name: versitygw
# https://www.versity.com/products/versitygw/
# https://github.com/versity/versitygw

services:
  # Versity Gateway - S3 Gateway
  versitygw:
    image: versity/versitygw:${VERSITYGW_IMAGE_TAG}
    container_name: versitygw
    depends_on:
      - versitygw-iam
    environment:
      - VGW_PORT=${VGW_WEBUI_S3_PORT}
      - VGW_BACKEND=${VGW_WEBUI_S3_BACKEND}
      - VGW_BACKEND_ARGS=${VGW_WEBUI_S3_BACKEND_ARGS}
      - VGW_VERSIONING_DIR=${VGW_WEBUI_S3_VERSIONING_DIR}
      - VGW_WEBUI_S3_PREFIX=${VGW_WEBUI_S3_PREFIX}
      - VGW_WEBUI_GATEWAYS=${VGW_WEBUI_GATEWAYS}
      - VGW_WEBUI_IAM_GATEWAYS=${VGW_WEBUI_IAM_GATEWAYS}
      - VGW_IAM_STANDALONE_ENDPOINT=${VGW_IAM_STANDALONE_ENDPOINT}
      - VGW_IAM_STANDALONE_DEFAULT_UID=${VGW_IAM_STANDALONE_DEFAULT_UID}
      - VGW_IAM_STANDALONE_DEFAULT_GID=${VGW_IAM_STANDALONE_DEFAULT_GID}
      - VGW_VIRTUAL_DOMAIN=${VGW_VIRTUAL_DOMAIN}
      - VGW_CORS_ALLOW_ORIGIN=${VGW_CORS_ALLOW_ORIGIN}
      - VGW_REGION=${VGW_REGION}
      - ROOT_ACCESS_KEY=${ROOT_ACCESS_KEY}
      - ROOT_SECRET_KEY=${ROOT_SECRET_KEY}
    networks:
      - versitygw-internal
    restart: unless-stopped
    volumes:
      - versitygw.data:/data
      - versitygw.run:/run/vgw

  # Versity Gateway - IAM Standalone Endpoint
  versitygw-iam:
    image: versity/versitygw:${VERSITYGW_IMAGE_TAG}
    container_name: versitygw-iam
    environment:
      - VGW_PORT=${VGW_IAM_PORT}
      - VGW_IAM_DIR=${VGW_IAM_DIR}
      - VGW_BACKEND=${VGW_IAM_BACKEND}
      - VGW_IAM_PRIVATE_PORTS=${VGW_IAM_PRIVATE_PORTS}
      - VGW_IAM_PRIVATE_SOCKET_PERM=${VGW_IAM_PRIVATE_SOCKET_PERM}
      - VGW_VIRTUAL_DOMAIN=${VGW_VIRTUAL_DOMAIN}
      - VGW_CORS_ALLOW_ORIGIN=${VGW_CORS_ALLOW_ORIGIN}
      - VGW_REGION=${VGW_REGION}
      - ROOT_ACCESS_KEY=${VERSITYGW_ROOT_ACCESS_KEY}
      - ROOT_SECRET_KEY=${VERSITYGW_ROOT_SECRET_KEY}
    networks:
      - versitygw-internal
    restart: unless-stopped
    volumes:
      - versitygw.iam:/data/iam
      - versitygw.run:/run/vgw

  # Caddy - Reverse Proxy
  versitygw-caddy:
    build:
      context: .
      dockerfile: ./caddy/Dockerfile
    container_name: versitygw-caddy
    environment:
      - BASE_URL=${BASE_URL}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - SSL_EMAIL=${SSL_EMAIL}
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - versitygw-internal
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - versitygw-caddy.data:/data

networks:
  # Local Network Proxied by Caddy with Let's Encrypt
  versitygw-internal:
    driver: bridge
    name: versitygw-internal

volumes:
  versitygw.data:
    name: versitygw.data
  versitygw.iam:
    name: versitygw.iam
  versitygw.run:
    name: versitygw.run
  versitygw-caddy.data:
    name: versitygw-caddy.data
