#-[ PROJECT NAME
name: grist
# https://www.getgrist.com/
# https://github.com/gristlabs/grist-core

services:
  # Postgres - SQL Database
  grist-postgres:
    image: postgres:${POSTGRES_IMAGE_TAG}
    container_name: grist-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - grist-backend
    restart: unless-stopped
    volumes:
      - grist-postgres.data:/var/lib/postgresql/data

  # Valkey - Key/Value Store
  grist-valkey:
    image: valkey/valkey:${VALKEY_IMAGE_TAG}
    container_name: grist-valkey
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 3s
    networks:
      - grist-backend
    restart: unless-stopped
    volumes:
      - grist-valkey.data:/data

  # Grist - Excel + Database
  grist:
    image: gristlabs/grist:${GRIST_IMAGE_TAG}
    container_name: grist
    cap_add:
      # Required for gVisor sandboxing
      - SYS_PTRACE
    depends_on:
      grist-postgres:
        condition: service_healthy
      grist-valkey:
        condition: service_healthy
    environment:
      - REDIS_URL=${REDIS_URL}
      - APP_HOME_URL=${APP_HOME_URL}
      - PORT=${PORT}
      - GRIST_SESSION_SECRET=${GRIST_SESSION_SECRET}
      - GRIST_WIDGET_LIST_URL=${GRIST_WIDGET_LIST_URL}
      - GRIST_ANON_PLAYGROUND=${GRIST_ANON_PLAYGROUND}
      - GRIST_SINGLE_ORG=${GRIST_SINGLE_ORG}
      - GRIST_SANDBOX_FLAVOR=${GRIST_SANDBOX_FLAVOR}
      - TYPEORM_TYPE=${TYPEORM_TYPE}
      - TYPEORM_HOST=${TYPEORM_HOST}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - GRIST_DEFAULT_EMAIL=${GRIST_DEFAULT_EMAIL}
      - GRIST_FORCE_LOGIN=${GRIST_FORCE_LOGIN}
      - GRIST_OIDC_IDP_ISSUER=${GRIST_OIDC_IDP_ISSUER}
      - GRIST_OIDC_IDP_CLIENT_ID=${GRIST_OIDC_IDP_CLIENT_ID}
      - GRIST_OIDC_IDP_CLIENT_SECRET=${GRIST_OIDC_IDP_CLIENT_SECRET}
      - GRIST_OIDC_SP_IGNORE_EMAIL_VERIFIED=${GRIST_OIDC_SP_IGNORE_EMAIL_VERIFIED}
    networks:
      # Default Port: 8484
      - cloudflare-ingress
      - grist-backend
    restart: unless-stopped
    volumes:
    - grist.data:/persist

networks:
  # Public / External Network (Cloudflare Tunnel)
  cloudflare-ingress:
    external: true
  # Storage / Backend Network (Not Accessible Externally)
  grist-backend:
    driver: bridge
    name: grist-backend

volumes:
  grist-postgres.data:
    name: grist-postgres.data
  grist-valkey.data:
    name: grist-valkey.data
  grist.data:
    name: grist.data
