#-[ PROJECT NAME
name: "zerobyte"

#-[ SERVICES
services:
  zerobyte:
    image: "ghcr.io/nicotsx/zerobyte:latest"
    container_name: "zerobyte"
    environment:
      - "TZ=America/Chicago"
    networks:
      - "cloudflare"
    restart: "unless-stopped"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "zerobyte.data:/var/lib/zerobyte"
      - "~/.config/rclone:/root/.config/rclone"
      - type: "bind"
        source: "/mnt/backups"
        target: "/remote"
        read_only: true
        bind:
          propagation: "shared"

#-[ NETWORKS
networks:
  # Public / External Network (Cloudflare Tunnel)
  cloudflare:
    external: true

#-[ VOLUMES
volumes:
  zerobyte.data:
