#-[ PROJECT NAME
name: termix
# https://termix.site/
# https://github.com/Termix-SSH/Termix

services:
  # Termix - Self-hosted SSH and remote desktop management
  termix:
    image: ghcr.io/lukegus/termix:${TERMIX_IMAGE_TAG}
    container_name: termix
    depends_on:
      - termix-guacd
    environment:
      - PORT=${PORT}
      - GUACD_HOST=${GUACD_HOST}
      - GUACD_PORT=${GUACD_PORT}
      - NODE_ENV=${NODE_ENV}
      - PUID=${PUID}
      - GUID=${GUID}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_KEY=${DATABASE_KEY}
      - INTERNAL_AUTH_TOKEN=${INTERNAL_AUTH_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL}
      - OIDC_ISSUER_URL=${OIDC_ISSUER_URL}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_SCOPES=${OIDC_SCOPES}
      - OIDC_ADMIN_GROUP=${OIDC_ADMIN_GROUP}
      - OIDC_GROUP_CLAIM=${OIDC_GROUP_CLAIM}
      - OIDC_FORCE_HTTPS=${OIDC_FORCE_HTTPS}
      - OIDC_ALLOW_REGISTRATION=${OIDC_ALLOW_REGISTRATION}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION}
      - ALLOW_PASSWORD_LOGIN=${ALLOW_PASSWORD_LOGIN}
      - ALLOW_PASSWORD_RESET=${ALLOW_PASSWORD_RESET}
    networks:
      # Default Port: 8080
      - cloudflare-ingress
      - termix-backend
    restart: unless-stopped
    volumes:
      - termix.data:/app/data

  # Guacamole - Open Source RDP
  termix-guacd:
    image: guacamole/guacd:${GUACD_IMAGE_TAG}
    container_name: termix-guacd
    networks:
      # Default Port: 4822
      - termix-backend
    restart: unless-stopped

networks:
  # Public / External Network (Cloudflare Tunnel)
  cloudflare-ingress:
    external: true
  # Storage / Backend Network (Not Accessible Externally)
  termix-backend:
    driver: bridge
    name: termix-backend

volumes:
  termix.data:
    name: termix.data
