# Either use TUNNEL_TOKEN and input the secret in plaintext or
# Create the docker secret first.
# Deploy mode is global, to ensure an instance of cloudflared is deployed to each worker.
# Using the same tunnel token allows Cloudflare to load balance at the front, where swarm
# will handle any routing in the back.
version: '3.8'

services:
  cloudflare:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${KC1_CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - cloudflare-ingress
    deploy:
      mode: global
      placement: 
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s

networks:
  cloudflare-ingress:
    driver: overlay
    name: cloudflare-ingress
    attachable: true