#-[ PROJECT NAME
name: samba
# https://github.com/dockur/samba

services:
  # Samba - SMB / CIFS - Great for backups across OS's
  samba:
    image: dockurr/samba:${SAMBA_IMAGE_TAG}
    container_name: samba
    environment:
      - NAME=${NAME}
      - USER=${USER}
      - PASS=${PASS}
    ports:
      - 445:445
    restart: unless-stopped
    volumes:
      - /var/lib/docker/volumes:/storage/backups/docker-volumes:ro
      - /srv/docker/backups/postgres:/storage/backups/postgres:ro
      - ./smb.conf:/etc/samba/smb.conf:ro
