#-[ PROJECT NAME
name: zerobyte
# https://zerobyte.app/
# https://github.com/nicotsx/zerobyte

services:
  # Zerobyte - Backups
  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:${ZEROBYTE_IMAGE_TAG:-latest}
    container_name: zerobyte
    environment:
      - TZ=America/Chicago
    networks:
      # Default Port: 4096
      - cloudflare-ingress
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - zerobyte.data:/var/lib/zerobyte
      - ~/.config/rclone:/root/.config/rclone
      - type: bind
        source: /mnt/backups
        target: /remote
        read_only: true
        bind:
          propagation: shared

networks:
  # Public / External Network (Cloudflare Tunnel)
  cloudflare-ingress:
    external: true

volumes:
  zerobyte.data:
    name: zerobyte.data
