#-[ STORAGE SETTINGS
metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"

#-[ CLUSTER SETTINGS
replication_factor = 1

# RPC is required for internal communication, even on a single node
rpc_bind_addr = "0.0.0.0:3901"
rpc_public_addr = "127.0.0.1:3901"
# Leave rpc_secret blank here so it can be injected via environment variables

#-[ S3 API SETTINGS
[s3_api]
api_bind_addr = "0.0.0.0:3900"
s3_region = "garage"
root_domain = ".s3.storage" # Required if planning to use virtual-host style bucket addressing

#-[ ADMINISTRATION API
# Expose this to allow workflows to provision new buckets and keys
[admin]
api_bind_addr = "0.0.0.0:3903"