#-[ PROJECT NAME
name: chatto
# https://chatto.run/
# https://github.com/chattocorp/chatto

services:
  # NATS - "Compact message broker that also ships with a built-in stream persistence engine"
  chatto-nats:
    image: nats:${NATS_IMAGE_TAG}
    container_name: chatto-nats
    command: ["--jetstream", "--store_dir=/data", "--auth=${NATS_TOKEN}"]
    healthcheck:
      test: ["CMD", "nats-server", "--help"]
      interval: 5s
      timeout: 3s
      retries: 3
    environment:
      - NATS_TOKEN=${NATS_TOKEN}
    networks:
      # Default Port: 4222
      - chatto-backend
    restart: unless-stopped
    volumes:
      - chatto-nats.data:/data

  chatto:
    # Chatto - Like Discord, but better. You also don't have to be The One for this.
    image: ghcr.io/chattocorp/chatto:${CHATTO_IMAGE_TAG}
    container_name: chatto
    depends_on:
      chatto-nats:
        condition: service_healthy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      # Default Port: 4000
      - cloudflare-ingress
      - chatto-backend
    volumes:
      - ./chatto.toml:/config/chatto.toml

networks:
  # Public / External Network (Cloudflare Tunnel)
  cloudflare-ingress:
    external: true
  # Storage / Backend Network (Not Accessible Externally)
  chatto-backend:
    driver: bridge
    name: chatto-backend

volumes:
  chatto-nats.data:
    name: chatto-nats.data
