#-[ PROJECT NAME
name: rustfs
# https://rustfs.com/
# https://github.com/rustfs/rustfs

services:
  # RustFS - S3 Storage
  rustfs:
    image: rustfs/rustfs:${RUSTFS_IMAGE_TAG}
    container_name: rustfs
    environment:
      - RUSTFS_ADDRESS=${RUSTFS_ADDRESS}
      - RUSTFS_CONSOLE_ADDRESS=${RUSTFS_CONSOLE_ADDRESS}
      - RUSTFS_CONSOLE_ENABLE=${RUSTFS_CONSOLE_ENABLE}
      - RUSTFS_ACCESS_KEY=${RUSTFS_ACCESS_KEY}
      - RUSTFS_SECRET_KEY=${RUSTFS_SECRET_KEY}
      - RUSTFS_SERVER_DOMAINS=${RUSTFS_SERVER_DOMAINS}
      - RUSTFS_BROWSER_REDIRECT_URL=${RUSTFS_BROWSER_REDIRECT_URL}
      - RUSTFS_IDENTITY_OPENID_ENABLE=${RUSTFS_IDENTITY_OPENID_ENABLE}
      - RUSTFS_IDENTITY_OPENID_CONFIG_URL=${RUSTFS_IDENTITY_OPENID_CONFIG_URL}
      - RUSTFS_IDENTITY_OPENID_CLIENT_ID=${RUSTFS_IDENTITY_OPENID_CLIENT_ID}
      - RUSTFS_IDENTITY_OPENID_CLIENT_SECRET=${RUSTFS_IDENTITY_OPENID_CLIENT_SECRET}
      - RUSTFS_IDENTITY_OPENID_SCOPES=${RUSTFS_IDENTITY_OPENID_SCOPES}
      - RUSTFS_IDENTITY_OPENID_REDIRECT_URI=${RUSTFS_IDENTITY_OPENID_REDIRECT_URI}
      - RUSTFS_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC=${RUSTFS_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC}
      - RUSTFS_IDENTITY_OPENID_DISPLAY_NAME=${RUSTFS_IDENTITY_OPENID_DISPLAY_NAME}
      - RUSTFS_IDENTITY_OPENID_GROUPS_CLAIM=${RUSTFS_IDENTITY_OPENID_GROUPS_CLAIM}
      - RUSTFS_IDENTITY_OPENID_EMAIL_CLAIM=${RUSTFS_IDENTITY_OPENID_EMAIL_CLAIM}
      - RUSTFS_IDENTITY_OPENID_USERNAME_CLAIM=${RUSTFS_IDENTITY_OPENID_USERNAME_CLAIM}
    networks:
      - cloudflare-ingress
      - rustfs-internal
    restart: unless-stopped
    volumes:
      - rustfs.data:/data

  # Caddy - Reverse Proxy
  rustfs-caddy:
    build:
      context: .
      dockerfile: ./caddy/Dockerfile
    container_name: rustfs-caddy
    environment:
      - BASE_URL=${BASE_URL}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - SSL_EMAIL=${SSL_EMAIL}
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - rustfs-internal
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - rustfs-caddy.data:/data

networks:
  # Public / External Network (Cloudflare Tunnel)
  cloudflare-ingress:
    external: true
  # Local Network Proxied by Caddy with Let's Encrypt
  rustfs-internal:
    driver: bridge
    name: rustfs-internal

volumes:
  rustfs.data:
    name: rustfs.data
  rustfs-caddy.data:
    name: rustfs-caddy.data
