#-[ PROJECT NAME
name: "komodo"

#-[ SERVICES
services:
   # Postgres - SQL Database
  komodo-postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:${POSTGRES_IMAGE_TAG}
    container_name: komodo-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    networks:
      - komodo-backend
    restart: unless-stopped
    volumes:
      - komodo-postgres.data:/var/lib/postgresql/data

  # FerretDB - MongoDB Adapter for Postgres With DocumentDB
  komodo-ferretdb:
    image: ghcr.io/ferretdb/ferretdb:${FERRETDB_IMAGE_TAG}
    container_name: komodo-ferretdb
    depends_on:
      - komodo-postgres
    environment:
      - FERRETDB_POSTGRESQL_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    networks:
      - komodo-backend
    restart: unless-stopped
    volumes:
      - komodo-ferretdb.state:/state

  # Komodo - Docker Application Stack Build and Deploy Utility
  komodo:
    image: ghcr.io/moghtech/komodo-core:${KOMODO_IMAGE_TAG}
    container_name: komodo
    init: true
    depends_on:
      - komodo-ferretdb
    env_file: ./.env
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    networks:
      - mbox-cloudflare
      - komodo-backend
    ports:
      - 9120:9120
    restart: unless-stopped
    volumes:
      - komodo.backups:/backups
      - komodo.keys:/config/keys

#-[ NETWORKS
networks:
  # Public / External Network (Cloudflare Tunnel)
  mbox-cloudflare:
    external: true
  # Storage / Backend Network (Not Accessible Externally)
  komodo-backend:
    driver: "bridge"

#-[ VOLUMES
volumes:
  komodo-postgres.data:
  komodo-ferretdb.state:
  komodo.backups:
  komodo.keys:
