#-[ PROJECT NAME
name: openssh-server
# https://docs.linuxserver.io/images/docker-openssh-server/
# https://github.com/linuxserver/docker-openssh-server

services:
  # OpenSSH Server - Useful for controlled directory mount
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:${OPENSSH_SERVER_IMAGE_TAG}
    container_name: openssh-server
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - SUDO_ACCESS=${SUDO_ACCESS}
      - PASSWORD_ACCESS=${PASSWORD_ACCESS}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - USER_PASSWORD=${USER_PASSWORD}
      - USER_NAME=${USER_NAME}
    ports:
      - 2222:2222
    restart: unless-stopped
    volumes:
      - /host/dir1:/container/dir1:ro
      - /host/dir2:/container/dir2:ro
