#-[ PROJECT NAME
name: uptime-kuma
# https://uptime.kuma.pet/
# https://github.com/louislam/uptime-kuma

services:
  # Uptime Kuma - Statuses, Notifications, Mayhem Regulator
  uptime-kuma:
    image: louislam/uptime-kuma:${UPTIME_KUMA_IMAGE_TAG:-beta}
    container_name: uptime-kuma
    networks:
      # Default Port: 3001
      - cloudflare-ingress
    restart: unless-stopped
    volumes:
      - uptime-kuma.data:/app/data

networks:
  # Public / External Network (Cloudflare Tunnel)
  cloudflare-ingress:
    external: true

volumes:
  uptime-kuma.data:
    name: uptime-kuma.data
