#-[ PROJECT NAME
name: portabase-agent
# https://portabase.io/docs/agent/setup
# https://github.com/Portabase/agent

services:
  app-portabase-agent:
    image: portabase/agent:${PORTABASE_AGENT_IMAGE_TAG:-latest}
    container_name: app-portabase-agent
    environment:
      - TZ=${TZ:-America/Chicago}
      - POLLING=${POLLING:-5}
      - APP_ENV=${APP_ENV:-production}
      - LOG=${LOG:-info}
      - EDGE_KEY=${EDGE_KEY}
    restart: unless-stopped
    networks:
      - app-postgres-backup
    volumes:
      - ./config.json:/config/config.json:ro

networks:
  app-postgres-backup:
    driver: bridge
    name: app-postgres-backup
