#-[ PROJECT NAME
name: coturn
# https://github.com/coturn/coturn

services:
  # Coturn - TURN Server
  coturn:
    image: coturn/coturn:${COTURN_IMAGE_TAG}
    container_name: coturn
    depends_on:
      coturn-caddy-certs:
        condition: service_healthy
    network_mode: host
    volumes:
      - coturn-caddy-certs.certs:/certs
    command:
      - -n
      - --fingerprint
      - --lt-cred-mech
      - --external-ip=${EXTERNAL_IP}
      - --realm=${BASE_URL}
      - --listening-ip=0.0.0.0
      - --listening-port=3578
      - --tls-listening-port=443
      - --min-port=51000
      - --max-port=60000
      - --cert=/certs/${BASE_URL}.crt
      - --pkey=/certs/${BASE_URL}.key
      - --user=${TURN_USER}:${TURN_PASSWORD}
      - --no-cli
      - --no-multicast-peers
      - --no-tlsv1_2

  # Caddy - Abused for Certificates
  coturn-caddy-certs:
    build:
      context: .
      dockerfile: ./caddy/Dockerfile
    container_name: coturn-caddy-certs
    environment:
      - BASE_URL=${BASE_URL}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - SSL_EMAIL=${SSL_EMAIL}
    restart: unless-stopped
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - coturn-caddy-certs.data:/data
      - coturn-caddy-certs.certs:/certs

volumes:
  coturn-caddy-certs.data:
    name: coturn-caddy-certs.data
  coturn-caddy-certs.certs:
    name: coturn-caddy-certs.certs
