#-[ PROJECT NAME
name: caddy-certs

services:
  # Caddy - Abused for Certificates
  caddy-certs:
    build:
      context: .
      dockerfile: ./caddy/Dockerfile
    container_name: caddy-certs
    environment:
      - BASE_URL=${BASE_URL}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - SSL_EMAIL=${SSL_EMAIL}
    restart: unless-stopped
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-certs.data:/data
      - caddy-certs.certs:/certs

volumes:
  caddy-certs.data:
    name: caddy-certs.data
  caddy-certs.certs:
    name: caddy-certs.certs
